services:
  familytree.app:
    container_name: FamilyTree.App
    image: ${DOCKER_REGISTRY-}familytree-app
    build:
      context: app
      dockerfile: Dockerfile
    networks:
      - familytree-network
    environment:
      API_URL: http://familytree.api:8080
      CLIENT_ID: super_secret_key
    ports:
      - "3000:3000"
        
  familytree.api:
    container_name: FamilyTree.Api
    image: ${DOCKER_REGISTRY-}familytree-api
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=familytree.db;Port=5432;Database=postgres;Username=postgres;Password=postgres
      - Authentication__Secret=super_secret_key
    depends_on:
      familytree.db:
        condition: service_healthy
    networks:
      - familytree-network
    ports:
      - "5251:8080"

  familytree.db:
    container_name: FamilyTree.Database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - familytree-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  familytree-network:
    driver: bridge
