//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Domain.Abstractions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FamilyTree.Domain.Abstractions.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Error_NullValue {
            get {
                return ResourceManager.GetString("Error_NullValue", resourceCulture);
            }
        }
        
        public static string Result_InvalidError {
            get {
                return ResourceManager.GetString("Result_InvalidError", resourceCulture);
            }
        }
        
        public static string Result_CanNotAccessValue {
            get {
                return ResourceManager.GetString("Result_CanNotAccessValue", resourceCulture);
            }
        }
        
        public static string Authentication_MissingHeader {
            get {
                return ResourceManager.GetString("Authentication_MissingHeader", resourceCulture);
            }
        }
        
        public static string Authentication_InvalidHeader {
            get {
                return ResourceManager.GetString("Authentication_InvalidHeader", resourceCulture);
            }
        }
        
        public static string Authentication_UnknownHeader {
            get {
                return ResourceManager.GetString("Authentication_UnknownHeader", resourceCulture);
            }
        }
    }
}
